# Numpy

## Lesson 1

### Importing numpy to the project

In [250]:
import numpy as np

### Creating numpy array

In [251]:
object = [1, 2, 3, 4]
np.array(object)

array([1, 2, 3, 4])

### Special features

### Getting entities from the array

In [252]:
array_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

array_3d[(1, 1, 1)]


18

### Changing entities in the array

In [253]:
array_3d[(1, 1, 1)] = 777
array_3d[(1, 1, 1)]

777

### Array from exact element

In [254]:
object = [1, 2, 3, 4, 5]
a = np.array(object)
a[[1, 1, 1, 1, 1, 1]]

array([2, 2, 2, 2, 2, 2])

### Boolean array

In [255]:
object = [1, 2, 3, 4, 5]
a = np.array(object)
a[[True, True, False, False, True]]

array([1, 2, 5])

### Reshape function

In [256]:
object = [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(object)
a.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Lesson 2

### Array function

In [257]:
some_array = np.array([1, 2, 3, 4, 5]) # Will create an array from a list

some_array1 = np.array((1, 2, 3, 4, 5)) # Will create an array from a tuple

some_array2 = np.array("Hello, World!") # Will create an array of strings from a string

### All data types in Numpy

In [258]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'ulong': numpy.uint64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex12

## Auto-fill functions

##### That`s how it is done without Numpy

In [259]:
np.array([0]*15)

np.array([x for x in range(15)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Empty function

In [260]:
np.empty((2, 4), "int32") # creates an empty mattrix

array([[-1717986918,  1069128089, -1717986918,  1070176665],
       [  858993459,  1070805811, -1717986918,  1071225241]], dtype=int32)

### Eye function

In [261]:
np.eye(4, 5, 0, "int32") # creates mattrix with 1 on the main diagonal

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int32)

### Identity function

In [262]:
np.identity(8, "int32") # creates square mattrix with 1 on the main diagonal

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

### Ones function

In [263]:
np.ones((8, 9), "int32") # creates  mattrix with 1 in all values

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

### Zeros function

In [264]:
np.zeros((8, 9), "int32") # creates mattrix with 0 in all the values

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

### Full function

In [265]:
np.full((3, 3), 777, "int32") # creates mattrix with 0 in all the values

array([[777, 777, 777],
       [777, 777, 777],
       [777, 777, 777]], dtype=int32)

## Mattrix creators

### mat function

In [266]:
np.mat('1 2 3 4') # creates mattrix from given values 1x4
np.mat('1, 2, 3, 4') # 1x4
np.mat('1, 2; 3, 4') # 2x4

matrix([[1, 2],
        [3, 4]])

### diag function

In [267]:
np.diag([1, 2, 3, 4])
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

### diagflat function

In [268]:
np.diagflat([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

### tri function

In [269]:
np.tri(4, 6)

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### tril function

In [270]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

### triu function

In [271]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### vander function

In [272]:

np.vander([1, 2, 3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

## Numeric diapasons

### arange function

In [273]:
np.arcange(8)

AttributeError: module 'numpy' has no attribute 'arcange'

### linspace function

In [ ]:
np.linspace(8, 20)

array([ 8. ,  9.2, 10.4, 11.6, 12.8, 14. , 15.2, 16.4, 17.6, 18.8, 20. ])

### logspace function

In [ ]:
np.logspace(8, 20, 4)

array([1.e+08, 1.e+12, 1.e+16, 1.e+20])

### geomspace function

In [ ]:
np.geomspace(8, 20, 4)

array([ 8.        , 10.85767047, 14.73612599, 20.        ])

## Copying arrays

### copy

In [ ]:
a = np.array([range(10)])
b = np.copy(a)
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### fromfunction

In [ ]:
a = np.array([range(10)])

def getRange(x, y):
    return 100*x + y

np.fromfunction(getRange, (2, 2))

array([[  0.,   1.],
       [100., 101.]])

### fromiter

In [ ]:
np.fromiter("Hello", dtype="U1")

array(['H', 'e', 'l', 'l', 'o'], dtype='<U1')

### fromstring

In [ ]:
np.fromstring("1;1;3", dtype="int32", sep=";")

array([1, 1, 3], dtype=int32)

## Array properties

### dtype

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a.dtype # returns data type of the array
a.dtype = np.float32 # changing data type property

dtype('int64')

### itemsize

In [ ]:
a.itemsize # returns the size of an array element

8

### ndim

In [ ]:
b = np.zeros((3, 3, 3, 4))
b.ndim # returns the dimentions of an array

3

### size

In [ ]:
b = np.zeros((3, 3, 3, 4))
b.size # returns the quanity of elements of the array

108

### shape

In [ ]:
b = np.zeros((3, 3, 3, 4))
b.shape # returns the shape of an array
b.shape = (4, 3, 3, 3)

In [ ]:
b = np.arange(100)
b.shape = -1, 5, 4 # the first parameter will be chosen automatically
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

### reshape

In [ ]:
b = np.zeros((3, 3, 3, 4))
c = b.reshape(1, 108)
"""
    b and c are still linked to the same array
"""

### transponate

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
d = b.T
"""
    b and d are still linked to the same data
"""
d[1] = 777
b

array([[  0, 777,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 777,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 777,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 777,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 777,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 777,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 777,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 777,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 777,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 777,  92,  93,  94,  95,  96,  97,  98,  99]])

### view()

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
c = b.T
"""
    c is linked to b directly
"""
c = b.view()
"""
    now c is linked to b`s data, but not to the b presentation directly
"""

array([[  0, 777,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 777,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 777,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 777,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 777,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 777,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 777,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 777,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 777,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 777,  92,  93,  94,  95,  96,  97,  98,  99]])

### copying an array`s data

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
c = np.array(b)
"""
    now c is not connected to b at all
"""

d = b.copy() #another way to create a copy

array([[  0, 777,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 777,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20, 777,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30, 777,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 777,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 777,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 777,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 777,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 777,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 777,  92,  93,  94,  95,  96,  97,  98,  99]])

### ravel

In [ ]:
b = np.arange((100))
b.shape = (10, 10)
b.ravel() # turning matrix into vector
b.shape = 10, 10
b.shape = -1 # The same result

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### resize

In [ ]:
b = np.arange((100))
b.resize(10, 10)
# This method does not return any values but changes the presentation of an array itself

b.resize(9, 9) # notice, that the number of elements is reduced
b.resize(100, 100) # notice, that the number of elements is increased
b

array([[0, 1, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### append and delete

In [ ]:
b = np.arange((100)).reshape(10, 10)
b = np.append(b, [[1, 2, 3, 777, 777, 777, 777, 777, 777, 777]], axis=0)
b = np.delete(b, 0, axis=0)
b

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [  1,   2,   3, 777, 777, 777, 777, 777, 777, 777]])

### expand_dims

In [ ]:
b = np.arange((100)).reshape(10, 10)
b = np.expand_dims(b, axis=0)
# a new axis is added to b
b = np.expand_dims(b, axis=-1)
# adds a new axis to the end of the array


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

### expand_dims

In [ ]:
b = np.arange((100)).reshape(10, 10)
b = np.expand_dims(b, axis=0)
# a new axis is added to b
b = np.expand_dims(b, axis=-1)
# adds a new axis to the end of the array


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

### squize

In [ ]:
b = np.arange((100)).reshape(10, 10)
b = np.expand_dims(b, axis=-1)
b = np.squeeze(b)
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### newaxis

In [ ]:
a = np.arange(100).reshape((10, 10))
b = a[np.newaxis, :]
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

## Merging arrays

### hstack

In [ ]:
# merges array by the 1 axis
a = np.array(((1, 2), (3, 4)))
b = np.array(((5, 6), (7, 8)))
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### vstack

In [ ]:
# merges array by the 0 axis
a = np.array(((1, 2), (3, 4)))
b = np.array(((5, 6), (7, 8)))
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### column_stack

In [ ]:
# merges vectors as columns
a = np.array(((1, 2, 3, 4))).reshape((-1))
b = np.array(((5, 6, 7, 8))).reshape((-1))
np.column_stack([a, b])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### row_stack

In [ ]:
# merges vectors as rows
a = np.array(((1, 2, 3, 4))).reshape((-1))
b = np.array(((5, 6, 7, 8))).reshape((-1))
np.row_stack([a, b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### concatinate

In [ ]:
a = np.arange(1, 13).reshape((3, 2, 2))
b = np.arange(13, 25).reshape((3, 2, 2))
c0 = np.concatenate((a, b), 0)
c1 = np.concatenate((a, b), 1)
c2 = np.concatenate((a, b), 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24]]])

### r_ and c_ objects

In [ ]:
a = np.arange(10).reshape((2, 5))
b = np.arange(10).reshape((2, 5))
np.r_[(a, b)] # concatinates along the 0 axis

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a = np.arange(10).reshape((2, 5))
b = np.arange(10).reshape((2, 5))
np.c_[(a, b)] # concatinates along the 1 axis

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

## Dividing arrays

### hsplit

In [ ]:
a = np.arange(10)
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
a = np.arange(100).reshape((10, 10))
np.hsplit(a, 10) # divides the horizontal axis

[array([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]]),
 array([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]]),
 array([[ 2],
        [12],
        [22],
        [32],
        [42],
        [52],
        [62],
        [72],
        [82],
        [92]]),
 array([[ 3],
        [13],
        [23],
        [33],
        [43],
        [53],
        [63],
        [73],
        [83],
        [93]]),
 array([[ 4],
        [14],
        [24],
        [34],
        [44],
        [54],
        [64],
        [74],
        [84],
        [94]]),
 array([[ 5],
        [15],
        [25],
        [35],
        [45],
        [55],
        [65],
        [75],
        [85],
        [95]]),
 array([[ 6],
        [16],
        [26],
        [36],
        [46],
        [56],
        [66],
        [76],
        [86],
        [96]]),
 array

### vsplit

In [ ]:
# divides the vertical axis
a = np.arange(100).reshape((10, 10))
np.vsplit(a, 5)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

### array_split

In [ ]:
# divides the array into N parts by a given axis
a = np.arange(200).reshape((2, 10, 10))
np.array_split(a, 5, axis=1)

[array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]],
 
        [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]]),
 array([[[ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]],
 
        [[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]]]),
 array([[[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],
 
        [[140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]]]),
 array([[[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],
 
        [[160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
         [170, 171, 172, 173, 174, 175, 176, 177, 178, 179]]]),


## Slices and indexes

In [ ]:
matrix = np.arange(100).reshape(10, 10)

In [ ]:
tensor = np.arange(1000).reshape(10, 10, 10)

### multidimesional slices

In [ ]:
matrix[1:3, 1:3]

array([[11, 12],
       [21, 22]])

In [ ]:
tensor [::5, ::2, ::2]

array([[[  0,   2,   4,   6,   8],
        [ 20,  22,  24,  26,  28],
        [ 40,  42,  44,  46,  48],
        [ 60,  62,  64,  66,  68],
        [ 80,  82,  84,  86,  88]],

       [[500, 502, 504, 506, 508],
        [520, 522, 524, 526, 528],
        [540, 542, 544, 546, 548],
        [560, 562, 564, 566, 568],
        [580, 582, 584, 586, 588]]])

In [ ]:
### These are equivalent
(tensor[..., 3] == tensor[:, :, 3])[0, 0]

True

### Boolean indexation

In [ ]:
# we can pass a python list of bools or a numpy array to take only True elements 
a = np.arange(5)
indexes = [True, True, False, True, False]
a[indexes]

array([0, 1, 3])

In [ ]:
# we can form a boolean array ourselves
a = np.arange(10)
i = a > 5
a[i]

array([6, 7, 8, 9])

In [ ]:
# a shortened form, but equivalent
a = np.arange(10)
a[a > 5]

array([6, 7, 8, 9])

### .any and .all

In [ ]:

a = np.arange(10)
np.any(a>5) # checks if at least one element of the array is true

True

In [ ]:

a = np.arange(10)
np.all(a>5) # checks if all elements of the array are true

False

### List indexation

In [ ]:
a = np.arange(100, 110)
b = a[[1, 3, 4, 8]]
b # it is a copy of a, not connected to the origin

array([101, 103, 104, 108])

In [ ]:
# we can change the value of a few elements by giving their indexes as a list
a = np.arange(10)
a[[1, 3, 5]] = 77777
a

array([    0, 77777,     2, 77777,     4, 77777,     6,     7,     8,
           9])

In [ ]:
# we can pass a python list of indexes or a numpy array of indexes 
a = np.arange(10, 20)
indexes = [1, 1, 2, 2, 6, 6]
a[indexes]

array([1, 1, 2, 2, 6, 6])

In [ ]:
#creating multi-dimensional arrays by list indexation os also possible
a = np.arange(10)
indexes = [[5, 6],[7, 8]]
a[indexes]

array([[5, 6],
       [7, 8]])

In [ ]:
# taking exact lines of a matrix or tensor is also possible
a = np.arange(100).reshape(10, 10)
indexes = [[1, 2]]
a[indexes]

array([[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]])

In [ ]:
# taking exact elements of a matrix or tensor is also possible
a = np.arange(100).reshape(10, 10)
lines = [1, 2] # selects 1 and 2 lines 
columns = [2, 3] # selects 3 and 2 columns
a[lines, columns]

array([12, 23])

## Math operations

In [ ]:
a = np.arange(5)
a + 10

array([10, 11, 12, 13, 14])

In [ ]:
a = np.arange(5)
a * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
a = np.arange(5)
a / 10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
a = np.arange(5)
a // 10

array([0, 0, 0, 0, 0])

In [ ]:
a = np.arange(5)
a % 2

array([0, 0, 0, 0, 0])

In [ ]:
a = np.arange(5)
a ** 2

array([ 0,  1,  4,  9, 16])

In [274]:
a = np.arange(5)
-a

array([ 0, -1, -2, -3, -4])

### Size restrictions

In [276]:
# a has the same row length as b, so the operation is possible
a = np.arange(5)
b = np.arange(10).reshape(2, 5)
a + b

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

### array_equal

In [277]:
# regular == returns ndarray
a = np.arange(5)
b = np.arange(10, 15)
a == b

array([False, False, False, False, False])

In [278]:
# array_equal returns bool
a = np.arange(5)
b = np.arange(10, 15)
np.array_equal(a, b)

False

### inf and nan

In [ ]:
a = np.array([1])
a / 0
# we get infinity as a result

/var/folders/8g/hrr0dtn57lb04xhx37szq0k00000gn/T/ipykernel_57224/3515800213.py:2: RuntimeWarning: divide by zero encountered in divide
  a / 0


array([inf])

In [282]:
a = np.array([np.inf])
a * 0
# we get nan as a result

/var/folders/8g/hrr0dtn57lb04xhx37szq0k00000gn/T/ipykernel_57224/4087425381.py:2: RuntimeWarning: invalid value encountered in multiply
  a * 0


array([nan])

In [285]:
a = np.array([np.inf, np.nan])
np.isinf(a) # looks for inf
np.isnan(a) # looks for nan


array([False,  True])

## Math operations

In [286]:
a = np.arange(5)
np.sum(a)

10

In [287]:
a = np.arange(5)
np.max(a)

4

In [291]:
a = np.arange(100)
np.mean(a)

49.5

In [290]:
a = np.arange(100).reshape(10, 10)
a.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [292]:
a = np.arange(100).reshape(10, 10)
a.max(axis=1)

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [297]:
a = np.arange(-100, 0).reshape(10, 10)
np.abs(a)

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [ ]:
a = np.array([2, 4, 1, 33, 23, 87])
np.argmax(a)
# returns the index of max element

5

### Random

In [342]:
a = np.array([2, 4, 1, 33, 23, 87])
np.random.rand(2, 3)
# random float from [0, 1)

array([[0.79785133, 0.84075511, 0.93288376],
       [0.70417431, 0.82119964, 0.73084678]])

In [341]:
a = np.array([2, 4, 1, 33, 23, 87])
np.random.randint(1, 10)
# random int from [1, 10]

7

In [344]:
a = np.arange(10)
np.random.shuffle(a)
a

array([6, 4, 7, 3, 5, 0, 8, 2, 1, 9])

In [ ]:
a = np.arange(10)
np.random.shuffle(a)
a

array([6, 4, 7, 3, 5, 0, 8, 2, 1, 9])

In [345]:
np.random.permutation(10)


array([7, 1, 9, 2, 8, 4, 0, 3, 6, 5])

### Statistics

In [ ]:
x = np.random.permutation(100)
y = np.random.permutation(100)

In [346]:
x = np.random.permutation(100)
np.median(x)

49.5

In [347]:
x = np.random.permutation(100)
np.var(x)

833.25

In [348]:
x = np.random.permutation(100)
np.std(x)

28.86607004772212

In [ ]:
x = np.random.permutation(100)
y = np.random.permutation(100)
xy = np.vstack((x, y))
np.corrcoef(xy)

array([[ 1.        , -0.11563156],
       [-0.11563156,  1.        ]])

In [353]:
x = np.random.permutation(100)
y = np.random.permutation(100)
xy = np.vstack((x, y))
np.cov(xy)

array([[841.66666667,  75.32323232],
       [ 75.32323232, 841.66666667]])

In [355]:
x = np.random.permutation(100)
y = np.random.permutation(100)
np.correlate(x, y)

array([255157])

## Linear algebra

### Transponate

In [357]:
a = np.arange(100).reshape(10, 10).T
a

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

### Matrix multiplition

In [359]:
a = np.arange(100).reshape(10, 10)
b = np.arange(100, 200).reshape(10, 10)
np.dot(a, b) # can also be used for scalar multiplition between vectors calculation

array([[  7350,   7395,   7440,   7485,   7530,   7575,   7620,   7665,
          7710,   7755],
       [ 21850,  21995,  22140,  22285,  22430,  22575,  22720,  22865,
         23010,  23155],
       [ 36350,  36595,  36840,  37085,  37330,  37575,  37820,  38065,
         38310,  38555],
       [ 50850,  51195,  51540,  51885,  52230,  52575,  52920,  53265,
         53610,  53955],
       [ 65350,  65795,  66240,  66685,  67130,  67575,  68020,  68465,
         68910,  69355],
       [ 79850,  80395,  80940,  81485,  82030,  82575,  83120,  83665,
         84210,  84755],
       [ 94350,  94995,  95640,  96285,  96930,  97575,  98220,  98865,
         99510, 100155],
       [108850, 109595, 110340, 111085, 111830, 112575, 113320, 114065,
        114810, 115555],
       [123350, 124195, 125040, 125885, 126730, 127575, 128420, 129265,
        130110, 130955],
       [137850, 138795, 139740, 140685, 141630, 142575, 143520, 144465,
        145410, 146355]])

In [360]:
a = np.arange(100).reshape(10, 10)
b = np.arange(100, 200).reshape(10, 10)
a @ b # the same result

array([[  7350,   7395,   7440,   7485,   7530,   7575,   7620,   7665,
          7710,   7755],
       [ 21850,  21995,  22140,  22285,  22430,  22575,  22720,  22865,
         23010,  23155],
       [ 36350,  36595,  36840,  37085,  37330,  37575,  37820,  38065,
         38310,  38555],
       [ 50850,  51195,  51540,  51885,  52230,  52575,  52920,  53265,
         53610,  53955],
       [ 65350,  65795,  66240,  66685,  67130,  67575,  68020,  68465,
         68910,  69355],
       [ 79850,  80395,  80940,  81485,  82030,  82575,  83120,  83665,
         84210,  84755],
       [ 94350,  94995,  95640,  96285,  96930,  97575,  98220,  98865,
         99510, 100155],
       [108850, 109595, 110340, 111085, 111830, 112575, 113320, 114065,
        114810, 115555],
       [123350, 124195, 125040, 125885, 126730, 127575, 128420, 129265,
        130110, 130955],
       [137850, 138795, 139740, 140685, 141630, 142575, 143520, 144465,
        145410, 146355]])

### Linalg module

In [ ]:
a = np.array([1, 2, 3, 1, 4, 9, 1, 8, 27]).reshape((3, 3))

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

### matrix rank

In [ ]:
np.linalg.matrix_rank(a) # gets the rank of a mattrix

3

### linear equasions system

In [365]:
a = np.array([1, 2, 3, 1, 4, 9, 1, 8, 27]).reshape((3, 3))
y = np.array((10, 20, 30))
np.linalg.solve(a, y)

array([-5.        , 10.        , -1.66666667])

### reverse matrix

In [366]:
a = np.array([1, 2, 3, 1, 4, 9, 1, 8, 27]).reshape((3, 3))
np.linalg.inv(a)

array([[ 3.        , -2.5       ,  0.5       ],
       [-1.5       ,  2.        , -0.5       ],
       [ 0.33333333, -0.5       ,  0.16666667]])

## Numpy sets

In [367]:
x = np.array((1, 2, 6, 3, 2, 77, 1, 66, 4, 3))
np.unique(x)

array([ 1,  2,  3,  4,  6, 66, 77])

In [368]:
# return counts also returns the number of reps
x = np.array((1, 2, 6, 3, 2, 77, 1, 66, 4, 3))
np.unique(x, return_counts=True)

(array([ 1,  2,  3,  4,  6, 66, 77]), array([2, 2, 2, 1, 1, 1, 1]))

In [ ]:
# return indexes of the first apperance in the array
x = np.array((1, 2, 6, 3, 2, 77, 1, 66, 4, 3))
np.unique(x, return_index=True)

(array([ 1,  2,  3,  4,  6, 66, 77]), array([0, 1, 3, 8, 2, 7, 5]))

In [370]:
# return indexes all elements in corresponding order
x = np.array((1, 2, 6, 3, 2, 77, 1, 66, 4, 3))
np.unique(x, return_inverse=True)

(array([ 1,  2,  3,  4,  6, 66, 77]), array([0, 1, 4, 2, 1, 6, 0, 5, 3, 2]))

In [372]:
# return only unique rows
x = np.array((1, 2, 3, 1, 2, 3, 4, 5, 6)).reshape(3, 3)
np.unique(x, axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

### in1d

In [ ]:
x = np.arange(5)
y = np.arange(10)
np.in1d(x, y) # checks if the elem from x is present in y

array([ True,  True,  True,  True,  True])

### intersect1d

In [374]:
x = np.arange(5)
y = np.arange(10)
np.intersect1d(x, y) # intersects x and y sets

array([0, 1, 2, 3, 4])

### setdiff1d

In [ ]:
x = np.arange(5)
y = np.arange(10)
np.setdiff1d(x, y) # substracts y from x

array([0, 1, 2, 3, 4])

### union1d

In [375]:
x = np.arange(5)
y = np.arange(10)
np.union1d(x, y) # unites the sets

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### setxor1d

In [376]:
x = np.arange(5)
y = np.arange(10)
np.setxor1d(x, y) # xor between x and y

array([5, 6, 7, 8, 9])

## Translating arrays

In [ ]:
# 0-dimentional translation
x = np.array([10])
y = np.arange(100)
x * y

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [ ]:
# 0-dimentional translation
x = np.array(10)
y = np.arange(100).reshape(10, 10)
y / x
# an axis was added to x, and x was translated downwards

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

## Sorting

In [ ]:
a = np.arange(100).reshape(10, 10)
np.sort(a, axis=-1, kind=None, order=None)

axis: Опциональный параметр, указывающий ось, по которой нужно провести сортировку. По умолчанию -1, что означает сортировку по последней оси.

kind: Опциональный параметр, определяющий алгоритм сортировки. Может принимать значения 'quicksort', 'mergesort', 'heapsort' или None. По умолчанию используется 'quicksort'.

order: Опциональный параметр, применяется при сортировке структурированных массивов. Может содержать названия полей и направления сортировки для каждого поля.

In [393]:
a = np.arange(100).reshape(10, 10)
np.delete(a, [0], axis=0)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])